// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetScenarioById(ctx context.Context, scenarioID uuid.UUID) (OnboardingScenario, error)
	GetScenarioByIdAndProjectKey(ctx context.Context, arg GetScenarioByIdAndProjectKeyParams) (OnboardingScenario, error)
	GetScenariosByPagePatternAndProjectkey(ctx context.Context, arg GetScenariosByPagePatternAndProjectkeyParams) ([]OnboardingScenario, error)
}

var _ Querier = (*Queries)(nil)
