// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scenario

import (
	"context"

	"github.com/google/uuid"
)

const getScenarioById = `-- name: GetScenarioById :one
SELECT s.id,
       s.project_id,
       s.name,
       s.description,
       s.page_pattern,
       s.status,
       s.published_at,
       s.created_at,
       s.updated_at,
       s.deleted_at
FROM onboarding.scenarios AS s
WHERE s.id = $1
  AND s.deleted_at IS NULL
`

func (q *Queries) GetScenarioById(ctx context.Context, scenarioID uuid.UUID) (OnboardingScenario, error) {
	row := q.db.QueryRow(ctx, getScenarioById, scenarioID)
	var i OnboardingScenario
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScenarioByIdAndProjectKey = `-- name: GetScenarioByIdAndProjectKey :one
SELECT s.id,
       s.project_id,
       s.name,
       s.description,
       s.page_pattern,
       s.status,
       s.published_at,
       s.created_at,
       s.updated_at,
       s.deleted_at
FROM onboarding.scenarios AS s
JOIN onboarding.projects AS p ON p.id = s.project_id
WHERE s.id = $1
  AND p.project_key = $2
  AND s.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type GetScenarioByIdAndProjectKeyParams struct {
	ScenarioID uuid.UUID `json:"scenario_id"`
	ProjectKey string    `json:"project_key"`
}

func (q *Queries) GetScenarioByIdAndProjectKey(ctx context.Context, arg GetScenarioByIdAndProjectKeyParams) (OnboardingScenario, error) {
	row := q.db.QueryRow(ctx, getScenarioByIdAndProjectKey, arg.ScenarioID, arg.ProjectKey)
	var i OnboardingScenario
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScenariosByPagePatternAndProjectkey = `-- name: GetScenariosByPagePatternAndProjectkey :many
SELECT s.id,
       s.project_id,
       s.name,
       s.description,
       s.page_pattern,
       s.status,
       s.published_at,
       s.created_at,
       s.updated_at,
       s.deleted_at
FROM onboarding.scenarios AS s
JOIN onboarding.projects AS p ON p.id = s.project_id
WHERE s.page_pattern = $1
  AND p.project_key = $2
  AND s.status = 'enabled'
  AND s.published_at <= NOW()
  AND s.deleted_at IS NULL
  AND p.deleted_at IS NULL
ORDER BY s.published_at, s.id
`

type GetScenariosByPagePatternAndProjectkeyParams struct {
	PagePattern string `json:"page_pattern"`
	ProjectKey  string `json:"project_key"`
}

func (q *Queries) GetScenariosByPagePatternAndProjectkey(ctx context.Context, arg GetScenariosByPagePatternAndProjectkeyParams) ([]OnboardingScenario, error) {
	rows, err := q.db.Query(ctx, getScenariosByPagePatternAndProjectkey, arg.PagePattern, arg.ProjectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnboardingScenario
	for rows.Next() {
		var i OnboardingScenario
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.PagePattern,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
