// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package step

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetStepsByScenarioId(ctx context.Context, scenarioID uuid.UUID) ([]GetStepsByScenarioIdRow, error)
}

var _ Querier = (*Queries)(nil)
