// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package step

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getStepsByScenarioId = `-- name: GetStepsByScenarioId :many
SELECT s.id AS scenario_id,
       s.name AS scenario_name,
       s.description AS scenario_description,
       s.page_pattern AS scenario_page_pattern,
       st.id AS step_id,
       st.step_num,
       st.title AS step_title,
       st.description AS step_description,
       st.frontend_data,
       e.id AS element_id,
       e.key AS element_key,
       e.label AS element_label,
       e.description AS element_description
FROM onboarding.scenarios AS s
LEFT JOIN onboarding.steps AS st
  ON st.scenario_id = s.id
 AND st.deleted_at IS NULL
LEFT JOIN onboarding.elements AS e
  ON e.id = st.element_id
 AND e.deleted_at IS NULL
WHERE s.id = $1
  AND s.deleted_at IS NULL
ORDER BY st.step_num, st.id
`

type GetStepsByScenarioIdRow struct {
	ScenarioID          uuid.UUID   `json:"scenario_id"`
	ScenarioName        string      `json:"scenario_name"`
	ScenarioDescription string      `json:"scenario_description"`
	ScenarioPagePattern string      `json:"scenario_page_pattern"`
	StepID              pgtype.UUID `json:"step_id"`
	StepNum             pgtype.Int4 `json:"step_num"`
	StepTitle           pgtype.Text `json:"step_title"`
	StepDescription     pgtype.Text `json:"step_description"`
	FrontendData        []byte      `json:"frontend_data"`
	ElementID           pgtype.UUID `json:"element_id"`
	ElementKey          pgtype.Text `json:"element_key"`
	ElementLabel        pgtype.Text `json:"element_label"`
	ElementDescription  pgtype.Text `json:"element_description"`
}

func (q *Queries) GetStepsByScenarioId(ctx context.Context, scenarioID uuid.UUID) ([]GetStepsByScenarioIdRow, error) {
	rows, err := q.db.Query(ctx, getStepsByScenarioId, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStepsByScenarioIdRow
	for rows.Next() {
		var i GetStepsByScenarioIdRow
		if err := rows.Scan(
			&i.ScenarioID,
			&i.ScenarioName,
			&i.ScenarioDescription,
			&i.ScenarioPagePattern,
			&i.StepID,
			&i.StepNum,
			&i.StepTitle,
			&i.StepDescription,
			&i.FrontendData,
			&i.ElementID,
			&i.ElementKey,
			&i.ElementLabel,
			&i.ElementDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
