// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package step

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingStep struct {
	ID           uuid.UUID          `json:"id"`
	ScenarioID   uuid.UUID          `json:"scenario_id"`
	ElementID    uuid.UUID          `json:"element_id"`
	StepNum      int32              `json:"step_num"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	FrontendData []byte             `json:"frontend_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
