// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package step

import (
	"context"

	"github.com/google/uuid"
)

const getStepById = `-- name: GetStepById :one
SELECT id, scenario_id, element_id, step_num, title, description, frontend_data, created_at, updated_at, deleted_at
FROM onboarding.steps
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStepById(ctx context.Context, id uuid.UUID) (OnboardingStep, error) {
	row := q.db.QueryRow(ctx, getStepById, id)
	var i OnboardingStep
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.ElementID,
		&i.StepNum,
		&i.Title,
		&i.Description,
		&i.FrontendData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
