// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package step

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetStepById(ctx context.Context, id uuid.UUID) (OnboardingStep, error)
}

var _ Querier = (*Queries)(nil)
