// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package projects

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingProject struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	ProjectKey string             `json:"project_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}
