// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package projects

import (
	"context"
)

const getProjectByProjectKey = `-- name: GetProjectByProjectKey :one
SELECT id,
       name,
       project_key,
       created_at,
       updated_at,
       deleted_at
FROM onboarding.projects
WHERE project_key = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectByProjectKey(ctx context.Context, projectKey string) (OnboardingProject, error) {
	row := q.db.QueryRow(ctx, getProjectByProjectKey, projectKey)
	var i OnboardingProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
