// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package session

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingSession struct {
	ID         uuid.UUID          `json:"id"`
	ScenarioID uuid.UUID          `json:"scenario_id"`
	UserID     string             `json:"user_id"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}
