// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package session

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changeSessionStatus = `-- name: ChangeSessionStatus :one
UPDATE onboarding.sessions
SET "status" = $1, "finished_at" = $2
WHERE "id" = $3 AND "status" = 'active'
RETURNING id, scenario_id, user_id, status, started_at, finished_at
`

type ChangeSessionStatusParams struct {
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) ChangeSessionStatus(ctx context.Context, arg ChangeSessionStatusParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, changeSessionStatus, arg.Status, arg.FinishedAt, arg.ID)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createOrGetActiveSession = `-- name: CreateOrGetActiveSession :one
INSERT INTO onboarding.sessions
  ("id", "scenario_id", "user_id", "status", "started_at", "finished_at")
VALUES
  ($1, $2, $3, 'active', $4, NULL)
ON CONFLICT ("scenario_id", "user_id") WHERE "status" = 'active'
DO UPDATE SET "user_id" = EXCLUDED."user_id"
RETURNING id, scenario_id, user_id, status, started_at, finished_at
`

type CreateOrGetActiveSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	ScenarioID uuid.UUID          `json:"scenario_id"`
	UserID     string             `json:"user_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateOrGetActiveSession(ctx context.Context, arg CreateOrGetActiveSessionParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, createOrGetActiveSession,
		arg.ID,
		arg.ScenarioID,
		arg.UserID,
		arg.StartedAt,
	)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const selectSessionById = `-- name: SelectSessionById :one
SELECT id, scenario_id, user_id, status, started_at, finished_at
FROM onboarding.sessions
WHERE "id" = $1
`

func (q *Queries) SelectSessionById(ctx context.Context, id uuid.UUID) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, selectSessionById, id)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
