// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package event

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingEvent struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	StepID     pgtype.UUID        `json:"step_id"`
	Type       string             `json:"type"`
	Data       []byte             `json:"data"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}
