// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package event

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (OnboardingEvent, error)
	GetEventByIdAndProjectKey(ctx context.Context, arg GetEventByIdAndProjectKeyParams) (GetEventByIdAndProjectKeyRow, error)
}

var _ Querier = (*Queries)(nil)
