// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package token

import (
	"context"
)

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id,
       scenario_id,
       hash,
       created_at,
       expires_at
FROM onboarding.scenario_test_tokens
WHERE hash = $1
  AND expires_at > NOW()
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash []byte) (OnboardingScenarioTestToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, hash)
	var i OnboardingScenarioTestToken
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
