// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package session

import (
	"context"

	"github.com/google/uuid"
)

const getSessionByScenarioAndUser = `-- name: GetSessionByScenarioAndUser :one
SELECT id,
       scenario_id,
       user_id,
       status,
       started_at,
       finished_at
FROM onboarding.sessions
WHERE scenario_id = $1
  AND user_id = $2
ORDER BY started_at DESC, id DESC
LIMIT 1
`

type GetSessionByScenarioAndUserParams struct {
	ScenarioID uuid.UUID `json:"scenario_id"`
	UserID     string    `json:"user_id"`
}

func (q *Queries) GetSessionByScenarioAndUser(ctx context.Context, arg GetSessionByScenarioAndUserParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, getSessionByScenarioAndUser, arg.ScenarioID, arg.UserID)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.UserID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
