// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package session

import (
	"context"
)

type Querier interface {
	GetSessionByScenarioAndUser(ctx context.Context, arg GetSessionByScenarioAndUserParams) (OnboardingSession, error)
}

var _ Querier = (*Queries)(nil)
