// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"context"
)

type Querier interface {
	GetScenarioByIdAndProjectKey(ctx context.Context, arg GetScenarioByIdAndProjectKeyParams) (OnboardingScenario, error)
}

var _ Querier = (*Queries)(nil)
