// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scenario

import (
	"context"

	"github.com/google/uuid"
)

const getScenarioByIdAndProjectKey = `-- name: GetScenarioByIdAndProjectKey :one
SELECT scenarios.id, scenarios.project_id, scenarios.name, scenarios.description, scenarios.page_pattern, scenarios.status, scenarios.published_at, scenarios.created_at, scenarios.updated_at, scenarios.deleted_at
FROM onboarding.scenarios AS scenarios
JOIN onboarding.projects AS projects ON projects.id = scenarios.project_id
WHERE scenarios.id = $1
  AND projects.project_key = $2
  AND scenarios.deleted_at IS NULL
  AND projects.deleted_at IS NULL
`

type GetScenarioByIdAndProjectKeyParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectKey string    `json:"project_key"`
}

func (q *Queries) GetScenarioByIdAndProjectKey(ctx context.Context, arg GetScenarioByIdAndProjectKeyParams) (OnboardingScenario, error) {
	row := q.db.QueryRow(ctx, getScenarioByIdAndProjectKey, arg.ID, arg.ProjectKey)
	var i OnboardingScenario
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
